config/routes.rb
SampleApp::Application.routes.draw do

 resources :relationships do
  end

  resources :users do
    member do
      get 'my_questionnaires'
    get 'my_answered_questionnaires'
    get 'shutdown'
    get 'reshut'
    end
  end
  
  resources :answers do
  end

  resources :questions do
  end

  resources :questionnaires do 
  member do 
    get 'open'
    get 'reopen'
    get 'close'
    get 'new_questions'
    get 'edit_questions'
    get 'show_answer'
    get 'preshow'
    get 'report'
    get 'set_limitations'
    get 'publishresult'
  end
end
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/create_url', to: 'static_pages#qrcode', via: 'get'
  match '/questionnaire_closed', to: 'static_pages#questionnaire_closed', via: 'get'
  match '/questionnaire_unpublished', to: 'static_pages#questionnaire_unpublished', via: 'get'
  match '/questionnaire_timeup', to: 'static_pages#questionnaire_timeup', via: 'get'
  match '/user_ip_limit', to: 'static_pages#user_ip_limit', via: 'get'
  match '/user_signin_limit', to: 'static_pages#user_signin_limit', via: 'get'
  match '/user_num_limit', to: 'static_pages#user_num_limit', via: 'get'
  match '/user_special_limit', to: 'static_pages#user_special_limit', via: 'get'
  match '/user_shutdown', to: 'static_pages#user_shutdown', via: 'get'
  match '/user_id_limit', to: 'static_pages#user_id_limit', via: 'get'
  match '/answer_successfully', to: 'static_pages#answer_successfully', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/questionnaire_info', to:'questionnaires#info', via: 'get'

 

end

app/models/user.rb
class User < ActiveRecord::Base
   has_many :questionnaires, :dependent => :destroy
   has_many :answers, :dependent => :destroy
   has_many :relationships, :dependent => :destroy

	before_save { self.user_email = user_email.downcase }
  before_create :create_remember_token

	validates :user_name , presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :user_email , presence: true, 
					   format: {with: VALID_EMAIL_REGEX}, 
             uniqueness: { case_sensitive: false }

  validates :user_age , presence: true
  validates_numericality_of :user_age, :integer_only=>true

  has_secure_password
  validates :password, length: { minimum: 6 }  

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end 

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.hash(User.new_remember_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]


  def index
     if !signed_in?
        redirect_to (user_id_limit_path) and return
      else
     if !admin?
      redirect_to (user_id_limit_path) and return
    end
  end
    @users = User.all
  end

  def new
  	@user = User.new
  end

  def show
  	
     if !signed_in?
        redirect_to (user_id_limit_path) and return
      else
        @user = User.find(params[:id])
    if !admin? && @user.id != current_user.id
      redirect_to (user_id_limit_path) and return
    end

  end
    @questionnaires = Questionnaire.where(qa_status: 1)
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success]="User deleted."
    redirect_to(:back)
  end 

  def create

    par = user_params

    par[:user_is_admin] = 0
    par[:user_status] = 0

    @user = User.new(par)    # Not the final implementation!

    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def shutdown
    @user = User.find(params[:id])
    
    if @user.user_status == 0
      @user.update_attribute(:user_status,1)
        redirect_to (:back)
    else 
        flash[:error] = "User already shut down"
        redirect_to (:back)
    end
  end

  def reshut
    @user = User.find(params[:id])
    
    if @user.user_status == 1
      @user.update_attribute(:user_status,0)
        redirect_to (:back)
    else 
        flash[:error] = "User status is normal"
        redirect_to (:back)
    end
  end

  def edit
 
    @user = User.find(params[:id])
     if !signed_in?
        redirect_to (user_id_limit_path) and return
      else
        if !admin? && @user.id != current_user.id
      redirect_to (user_id_limit_path) and return
    end
  end
  end

  def update

    @user = User.find(params[:id])
     if !signed_in?
        redirect_to (user_id_limit_path) and return
      else
        if !admin? && @user.id != current_user.id
      redirect_to (user_id_limit_path) and return
    end
  end
    if @user
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
    else 
      flash[:error] = "Old password is not correct"
      render 'edit'
    end
  end

  def my_questionnaires

    
     if !signed_in?
        redirect_to (user_id_limit_path) and return
      else
        @user = User.find(params[:id])
        if !admin? && @user.id != current_user.id
      redirect_to (user_id_limit_path) and return
    end
  end
    @questionnaires = @user.questionnaires
  end

  def my_answered_questionnaires

    
     if !signed_in?
        redirect_to (user_id_limit_path) and return
      else
        @user = User.find(params[:id])
        if !admin? && @user.id != current_user.id
      redirect_to (user_id_limit_path) and return
    end
  end
    @relationships = @user.relationships
  end

  private
    def user_params
      params.require(:user).permit(:user_name, :user_email, :password, :password_confirmation, :user_age, :user_sex, :user_job)
    end

    def signed_in_user
      
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
    	gravatar_id = Digest::MD5::hexdigest(user.user_email.downcase)
    	gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    	image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  end
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>编辑用户资料</h1>

<div class="row">
  <div class="span6 offset3">
    <div class="hero-unit" style="height:550px">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :user_name , "昵称" %>
      <%= f.text_field :user_name %>

      <%= f.label :user_email , "邮箱" %>
      <%= f.text_field :user_email %>

      <%= f.label :password , "新密码" %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "确认新密码" %>
      <%= f.password_field :password_confirmation %>

      <%= f.label :user_age , "年龄"%>
      <%= f.text_field :user_age %>

      <%= f.label :user_age , "性别"%>
      <%= f.select :user_sex, options_for_select([['男', '男'],['女', '女']]) %>

      <%= f.label :user_job , "职业" %>
      <%= f.text_field :user_job %>
<div align="center">
          <br />
      <%= f.submit "保存", class: "btn btn-large btn-primary" %>
    </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>用户管理</h1>
<!-- f.submit "Create new Questionnaire", class: 用户管理btn btn-large btn-primary"  -->

<table class="table table-striped table-hover">
   <thead>
      <tr>
         <th>用户名</th>
         <th>邮箱</th>
         <th>注册时间</th>
         <th>状态</th>
         <th>发布问卷数</th>
         <th>回答问卷数</th>
         <th>操作</th>
      </tr>
   </thead>

   <tbody>
   	<% @users.each do |user| %>
   	<% if user.id != current_user.id %>
	<tr>
	<td> <%= link_to user.user_name, user_path(user.id) %> </td>
	<td> <%= user.user_email %> </td>
	<td> <%= user.created_at %> </td>
	<td> <% if user.user_status == 0 %> 
		 <p>正常</p>
		 <% else %>
		 <p> 封禁</p>
		 <% end %>
	</td>
	<td> 
		<%= user.questionnaires.count %>
	</td>
	<td>
		<%= user.relationships.count %>
	</td>
	<td>
		<% if user.user_status == 0 %> 
		<%= link_to '封禁', shutdown_user_path(user.id) , :class=>"btn btn-mini" %>
		<% else %>
		<%= link_to '解封', reshut_user_path(user.id) , :class=>"btn btn-mini" %>
		<% end %>
		<%= link_to '删除', user, method: :delete, :class=>"btn btn-mini btn-danger" , data: { confirm: '确定删除用户吗?' } %>
	</td>
	</tr>
	<% end %>
     <% end %>
   </tbody>
</table>

app/views/users/my_answered_questionnaires.html.erb
<h1><%= current_user.user_name %>的答卷列表</h1>
<!-- f.submit "Create new Questionnaire", class: "btn btn-large btn-primary"  -->
<table class="table table-striped table-hover">
   <!--<caption><%= current_user.user_name %>'s AnsweredQuestionnaire</caption>-->
   <thead>
      <tr>
         <th>标题</th>
         <th>状态</th>
         <th>答卷时间</th>
         <th>查看答卷</th>
         <th>统计结果</th>
      </tr>
   </thead>

   <tbody>
   	<% @relationships.each do |relationship|
   	   @questionnaire = Questionnaire.find(relationship.questionnaire_id)
   	 %>
	<tr>
		<td><%= @questionnaire.qa_title %></td> 
		<td> 
			<% if @questionnaire.qa_status == 0 %>
			<p> 未发布</p>
			<% elsif @questionnaire.qa_status == 1 %>
			<p> 发布中</p>
			<%else%>
			<p> 已关闭</p>
			<%end%>
		</td>
		<td><%= relationship.created_at %></td> 
		<td><%= link_to '查看答卷', show_answer_questionnaire_path(@questionnaire.id) %>
		<td>			
			<% if @questionnaire.qa_status == 3 %>
			<%= link_to '查看结果', report_questionnaire_path(@questionnaire.id) %>
			<%else%>
			<p>结果未公布</p>
			<%end%>
		</td>
	</tr>
     <% end %>
   </tbody>
</table>

app/views/users/my_questionnaires.html.erb
<h1><%= current_user.user_name %>的问卷列表</h1>
<!-- f.submit "Create new Questionnaire", class: "btn btn-large btn-primary"  -->

<table class="table table-striped table-hover">
   <!--label style="font-size:20px"><%= current_user.user_name %>的问卷列表</label-->
   <thead>
      <tr>
         <th>标题（点击预览）</th>
         <th>主题</th>
         <th>创建时间</th>
         <th>状态</th>
         <th>回答数</th>
         <th>统计结果</th>
         <th>操作</th>
      </tr>
   </thead>

   <tbody>
   	<% @questionnaires.each do |questionnaire| %>
	<tr>
		<td><%= link_to questionnaire.qa_title, preshow_questionnaire_path(questionnaire.id) %></td> 
		<td><%= questionnaire.qa_subject %></td>
		<td><%= questionnaire.updated_at %></td>
		<td> 
			<% if questionnaire.qa_status == 0 %>
			<p> 未发布</p>
			<% elsif questionnaire.qa_status == 1 %>
			<p> 发布中</p>
			<%else%>
			<p> 已关闭</p>
			<%end%>
		</td>
		<td><%= questionnaire.relationships.count%></td>
		<td>			
			<% if questionnaire.qa_status == 2 %>
			<%= link_to '结果未公布，点击公布', publishresult_questionnaire_path(questionnaire.id) %>
			<%elsif questionnaire.qa_status == 3%>
			<p>结果已公布</p>
			<%elsif questionnaire.qa_status == 1 %>
			<p>问卷发布中，不能公布结果</p>
			<% else %>
			<p>问卷未发布，无结果</p>
			<%end%>
		</td>
		
		<td> 
			<% if questionnaire.qa_status == 0 %>
			<%= link_to '发布', open_questionnaire_path(questionnaire.id),:class=>"btn btn-mini"%>
			<%= link_to '编辑', edit_questionnaire_path(questionnaire.id), :class=>"btn btn-mini"%>
			<%= link_to '删除', questionnaire, method: :delete, data: {confirm: '是否确认删除:'+questionnaire.qa_title + '?'},  :class=>"btn btn-mini btn-danger" %>
			<% elsif questionnaire.qa_status == 1 %>
			<%= link_to '关闭', close_questionnaire_path(questionnaire.id),:class=>"btn btn-mini"%>
			<%= link_to '统计', report_questionnaire_path(questionnaire.id), :class=>"btn btn-mini"%>
			<%= link_to '删除', questionnaire, method: :delete, data: {confirm: '是否确认删除？'},  :class=>"btn btn-mini btn-danger" %>
			<% else %>
			<%= link_to '重开', open_questionnaire_path(questionnaire.id), :class=>"btn btn-mini" %>
			<%= link_to '统计', report_questionnaire_path(questionnaire.id), :class=>"btn btn-mini"%>
			<%= link_to '删除', questionnaire, method: :delete, data: {confirm: '是否确认删除？'},  :class=>"btn btn-mini btn-danger" %>
			<% end %>
		</td>
	</tr>
     <% end %>
   </tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<script type="text/javascript">

  function showinfo(id_name)
  {
        $('#name').popover('hide');
        $('#email').popover('hide');
        $('#password').popover('hide');
        $('#password_again').popover('hide');
        $('#age').popover('hide');
        $('#job').popover('hide');
        $('#'+id_name).popover('show');
  }

</script>
<h1>注册</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="hero-unit">
        <div>
          <%= f.label :user_name , "昵称", :style=>"font-size:16px" %>
          <%= f.text_field :user_name,  :style=>"width:100%", :id=>"name", :onfocus=>"showinfo(\"name\");", "data-toggle"=>"popover" ,"title"=>"", "data-content"=>"这是您在系统中显示的名称", "data-original-title"=>"昵称"%>
        </div>
        <div>
          <%= f.label :user_email , "邮箱" , :style=>"font-size:16px"%>
          <%= f.text_field :user_email,  :style=>"width:100%", :id=>"email", :onfocus=>"showinfo(\"email\");", "data-toggle"=>"popover" ,"title"=>"", "data-content"=>"您的邮箱同时也是您的登录帐号，请妥善保存", "data-original-title"=>"邮箱" %>
        </div>
        <div>
          <%= f.label :password , "密码" , :style=>"font-size:16px"%>
          <%= f.password_field :password,  :style=>"width:100%", :id=>"password", :onfocus=>"showinfo(\"password\");", "data-toggle"=>"popover" ,"title"=>"", "data-content"=>"您用于登录本系统的密码", "data-original-title"=>"密码" %>
        </div>
        <div>
          <%= f.label :password_confirmation, "再次输入密码" %>
          <%= f.password_field :password_confirmation,  :style=>"width:100%", :style=>"font-size:16px", :id=>"password_again", :onfocus=>"showinfo(\"password_again\");", "data-toggle"=>"popover" ,"title"=>"", "data-content"=>"再次输入您的密码，请确定它与第一次输入的密码一致", "data-original-title"=>"再次输入密码" %>
        </div>
        <div>
          <%= f.label :user_age , "年龄", :style=>"font-size:16px"%>
          <%= f.text_field :user_age,  :style=>"width:100%", :id=>"age", :onfocus=>"showinfo(\"age\");", "data-toggle"=>"popover" ,"title"=>"", "data-content"=>"请输入您的年龄", "data-original-title"=>"年龄"%>
        </div>
        <div>
          <%= f.label :user_sex , "性别", :style=>"font-size:16px"%>
          <%= f.select :user_sex, options_for_select([['男', '男'],['女', '女']]) %>
        </div>
        <div>
          <%= f.label :user_job , "职业", :style=>"font-size:16px" %>
          <%= f.text_field :user_job,  :style=>"width:100%", :style=>"font-size:16px", :id=>"job", :onfocus=>"showinfo(\"job\");", "data-toggle"=>"popover" ,"title"=>"", "data-content"=>"请输入您的职业，如学生、上班族等", "data-original-title"=>"职业" %>
        </div>
        <div align="center">
          <br />
          <%= f.submit "创建我的账户", class: "btn btn-large btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<script type="text/javascript">
                function showinfo(id_name)
                {   
                   $("#collapse"+id_name).collapse('toggle');
                }
            </script>
<% provide(:title, @user.user_name) %>

<div class="row">
  <section style="margin-left:30px;font-size:20px;font-weight:bold;">
    <%= gravatar_for @user %>
        <%= @user.user_name%>
        </section>
  <aside class="span4">
         <div class="row">
  <div class="span4 offset0 panel" style="float:left" >
      <div class="hero-unit">
        <div >
          <p>昵称:
          <%= @user.user_name %></p>
        </div>
        <div>
        	<p>邮箱:
          <%= @user.user_email %></p>
        </div>
        <div>
        	<p>年龄:
          <%= @user.user_age %></p>
        </div>
        <div>
        	<p>性别:
          <%= @user.user_sex %></p>
        </div>
        <div>
        	<p>职业:
          <%= @user.user_job %></p>
        </div>
      </div>
</div>
  </aside>
  <div align="center" class="well well-small panel" style="background:#ffffff;width:600px;margin-left:340px" >
<div>
    <div style="font-size:15px;font-weight:bold"><h3>我们为您挑选的问卷 </h3 ></div>
</div>

<div class="accordion" id="accordion2">
  <% @questionnaires.each do |questionnaire| %>
  <div class="accordion-group">
    <div class="accordion-heading" style="background:#F0F0F0">
       <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne" onclick="showinfo(<%=questionnaire.id%>)" style="color:#282828">
              
               <%= questionnaire.qa_title%>
       </a>
     </div>
     <div id="collapse<%=questionnaire.id%>" class="accordion-body collapse">
       <div class="accordion-inner" style="background:#FAFAFA">
              <p>主题：<%= questionnaire.qa_subject%></p>
              <p>描述：<%= questionnaire.qa_description%></p>
              <a href="/questionnaires/<%= questionnaire.id%>">点此作答</a>
       </div>
     </div>
  </div>
<% end %>
</div>
</div>
</div>
  