config/routes.rb
SampleApp::Application.routes.draw do

 resources :relationships do
  end

  resources :users do
    member do
      get 'my_questionnaires'
    get 'my_answered_questionnaires'
    get 'shutdown'
    get 'reshut'
    end
  end
  
  resources :answers do
  end

  resources :questions do
  end

  resources :questionnaires do 
  member do 
    get 'open'
    get 'reopen'
    get 'close'
    get 'new_questions'
    get 'edit_questions'
    get 'show_answer'
    get 'preshow'
    get 'report'
    get 'set_limitations'
    get 'publishresult'
  end
end
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  match '/home', to: 'static_pages#home', via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/create_url', to: 'static_pages#qrcode', via: 'get'
  match '/questionnaire_closed', to: 'static_pages#questionnaire_closed', via: 'get'
  match '/questionnaire_unpublished', to: 'static_pages#questionnaire_unpublished', via: 'get'
  match '/questionnaire_timeup', to: 'static_pages#questionnaire_timeup', via: 'get'
  match '/user_ip_limit', to: 'static_pages#user_ip_limit', via: 'get'
  match '/user_signin_limit', to: 'static_pages#user_signin_limit', via: 'get'
  match '/user_num_limit', to: 'static_pages#user_num_limit', via: 'get'
  match '/user_special_limit', to: 'static_pages#user_special_limit', via: 'get'
  match '/user_shutdown', to: 'static_pages#user_shutdown', via: 'get'
  match '/user_id_limit', to: 'static_pages#user_id_limit', via: 'get'
  match '/answer_successfully', to: 'static_pages#answer_successfully', via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/questionnaire_info', to:'questionnaires#info', via: 'get'

 

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
      <p>版权所有：软件学院Fireflies团队 地址：北京市海淀区学院路37号 邮编：100191</p>
  </small>
  <nav>
    <ul><small>
      <li><a href="http://soft.buaa.edu.cn/">北航软件学院</a></li>
      <li><%= link_to "关于我们", about_path %></li>
      <li><%= link_to "帮助", help_path %></li>
    </small></ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "FireFlies问卷调查", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if signed_in? %>
          <li><%= link_to "首页", root_path %></li>
          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 问卷<b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "创建问卷", new_questionnaire_path %></li>
                <li class="divider"></li>
                <li><%= link_to "我的问卷", my_questionnaires_user_path(current_user) %></li>
                <li><%= link_to "我的答卷", my_answered_questionnaires_user_path(current_user) %></li>
              </ul>
          </li>
          
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 账户<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "我的主页", @current_user %></li>
               <li><%= link_to "我的资料", edit_user_path(current_user) %></li>
               <li class="divider"></li>
               <li><%= link_to "注销", signout_path, method: "delete" %></li>
              </ul>
          </li>
          <% if admin?%>
            <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                管理<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><%= link_to "管理用户", users_path%></li>
               <li><%= link_to "管理问卷",  questionnaires_path%></li>
               <li><%= link_to "统计信息", questionnaire_info_path %></li>
              </ul>
          </li>
          <% end %>
          <% else %>
            <li><%= link_to "登录", signin_path %></li>
            <li><%= link_to "注册", signup_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  	<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %><!-- debug-->
    </div>
  </body>
</html>